"use client";

import { FormEvent, useMemo, useState } from "react";

type Book = { key: string; title?: string; author_name?: string[]; first_publish_year?: number; cover_i?: number; ebook_access?: string; ia?: string[]; publisher?: string[] };
const coverUrl = (id?: number) => id ? `https://covers.openlibrary.org/b/id/${id}-M.jpg` : "https://placehold.co/180x250/111827/93c5fd?text=No+Cover";

export default function Home() {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Book[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [access, setAccess] = useState("all"); const [sort, setSort] = useState("relevance");
  async function searchBooks(event?: FormEvent) { event?.preventDefault(); const trimmed=query.trim(); if(!trimmed)return; setLoading(true);setError(""); try{const response=await fetch(`/api/search?q=${encodeURIComponent(trimmed)}`);if(!response.ok)throw new Error("Search service is unavailable right now.");const data=await response.json();setResults(data.docs??[]);}catch(err){setResults([]);setError(err instanceof Error?err.message:"Something went wrong.");}finally{setLoading(false);} }
  const filteredResults=useMemo(()=>{const filtered=results.filter(book=>access==="readable"?book.ebook_access==="public"||(book.ia?.length??0)>0:access==="borrow"?book.ebook_access==="borrowable":true);if(sort==="year")return[...filtered].sort((a,b)=>(b.first_publish_year??0)-(a.first_publish_year??0));if(sort==="title")return[...filtered].sort((a,b)=>(a.title??"").localeCompare(b.title??""));return filtered;},[results,access,sort]);
  return <main className="page-shell"><nav className="nav"><a className="brand" href="#">📚 BookFinder <span>AI</span></a><div className="nav-links"><a href="#results">Browse</a><a href="#features">Features</a><a href="/pricing">Pro AI</a><a className="signin" href="/pricing">Unlock Pro</a></div></nav>
    <section className="hero"><div className="badge">✦ The student research engine</div><h1>Find books.<br/><span>Read & learn here.</span></h1><p>Search books and legitimate digital reading sources in one place. When a verified online copy is available, open it in BookFinder's built-in reader without leaving the site.</p><form className="search-box" onSubmit={searchBooks}><span className="search-icon">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by book, author, ISBN, or topic..." aria-label="Book search"/><button type="submit">Search</button></form><div className="quick-searches">Try: <button type="button" onClick={()=>setQuery("Atomic Habits")}>Atomic Habits</button><button type="button" onClick={()=>setQuery("physics")}>Physics</button><button type="button" onClick={()=>setQuery("machine learning")}>Machine learning</button></div><div className="hero-stats"><span><b>Millions</b> of catalog records</span><span><b>In-site reader</b> for verified copies</span><span><b>Pro AI</b> source synthesis</span></div></section>
    <section id="results" className="results-section"><div className="section-heading"><div><p className="eyebrow">DISCOVER</p><h2>{results.length?`${filteredResults.length} books found`:"Your research library"}</h2></div>{results.length>0&&<div className="filters"><select value={access} onChange={e=>setAccess(e.target.value)}><option value="all">All access</option><option value="readable">Read online</option><option value="borrow">Borrow</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="relevance">Relevance</option><option value="year">Newest</option><option value="title">Title</option></select></div>}</div>
      {loading&&<div className="status"><span className="spinner"/> Searching library records…</div>}{error&&<div className="status error">{error}</div>}{!loading&&!error&&results.length===0&&<div className="empty"><div className="empty-icon">✦</div><h3>Search for a book, topic, or author</h3><p>Find titles, authors, publication details, covers, and verified reading or borrowing options.</p></div>}
      <div className="book-grid">{filteredResults.map(book=>{const readId=book.ia?.[0];const openUrl=`https://openlibrary.org${book.key}`;return <article className="book-card" key={book.key}><img src={coverUrl(book.cover_i)} alt="" loading="lazy"/><div className="book-info"><div className="book-title">{book.title??"Untitled"}</div><div className="author">{book.author_name?.slice(0,2).join(", ")||"Unknown author"}</div><div className="meta">{book.first_publish_year||"Year unknown"}{book.publisher?.[0]?` · ${book.publisher[0]}`:""}</div><div className="card-actions">{readId?<><a className="read-btn" href={`/reader?archive=${encodeURIComponent(readId)}&title=${encodeURIComponent(book.title??"Book reader")}>Read here</a><a className="source-link" href={`https://archive.org/details/${readId}`} target="_blank" rel="noreferrer">Source ↗</a></>:<a className="outline-btn" href={openUrl} target="_blank" rel="noreferrer">View editions ↗</a>}</div></div></article>})}</div></section>
    <section id="features" className="features"><div><div className="feature-icon">⌕</div><h3>Deep discovery</h3><p>Search titles, authors, ISBNs and topics with library-powered results and useful filters.</p></div><div><div className="feature-icon">▣</div><h3>Read here</h3><p>When a verified Internet Archive reading copy is available, BookFinder opens its embedded reader inside our site. We do not host or bypass access controls.</p></div><div><div className="feature-icon">✦</div><h3>Pro AI Research</h3><p>Upgrade for an advanced research workspace that can organize sources, explain difficult material and help build assignment-ready study notes.</p><a className="feature-link" href="/pricing">See Pro →</a></div></section>
    <section className="pro-banner"><div><p className="eyebrow">BOOKFINDER PRO</p><h2>One workspace for serious students.</h2><p>Bring multiple books, reports, magazines and summaries into one AI-assisted research workflow.</p></div><a href="/pricing">Get Pro for $5/mo →</a></section><footer>BookFinder AI · Built for students · Search powered by Open Library · Verified reading sources are embedded where permitted · Pro payments use USDT on TRON</footer></main>;
}
